# Generated by Django 3.1.4 on 2020-12-27 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameness', '0002_auto_20201223_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='hold_card',
            field=models.TextField(default='{}'),
        ),
    ]
