# Generated by Django 3.1.4 on 2020-12-28 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameness', '0003_game_hold_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='open_turn',
            field=models.BooleanField(default=False),
        ),
    ]
