# Generated by Django 3.1.4 on 2020-12-29 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameness', '0004_game_open_turn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='hold_card',
        ),
        migrations.RemoveField(
            model_name='game',
            name='open_turn',
        ),
        migrations.AddField(
            model_name='turn',
            name='hold_card',
            field=models.TextField(default='{}'),
        ),
        migrations.AddField(
            model_name='turn',
            name='open_turn',
            field=models.BooleanField(default=False),
        ),
    ]
