# Generated by Django 3.1.4 on 2021-01-12 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameness', '0006_auto_20210107_1937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='suspected',
        ),
    ]
